---

- name: Install dependencies
  apt: pkg=python-pip
  when: ansible_os_family == 'Debian'

- name: Install dependencies(Redhat)
  yum: name="{{ item }}" state=latest
  with_items:
    - 'python-setuptools'
  when: ansible_os_family == 'RedHat'

- name: Install dependencies(Redhat)
  command: easy_install pip
  when: ansible_os_family == 'RedHat'


- name: Install supervisor
  pip: name=supervisor version={{ supervisor_version }}
  notify:
    - supervisor restart
    
- name: Install superlance
  pip: name=superlance
  when: supervisor_superlance

- name: Prepare directories
  file: state=directory path={{item}}
  with_items:
    - "{{supervisor_cfgdir}}"
    - "{{supervisor_logdir}}"
    - "{{supervisor_incdir}}"

- name: Configure supervisor - pt. 1
  template: src=supervisord.conf.j2 dest={{supervisor_conf_file}} owner=root group=root mode=0644
  notify:
    - supervisor restart

#- name: Configure supervisor - pt. 2
  #template: src=supervisor.conf.j2 dest=/etc/init/supervisor.conf owner=root group=root mode=0755

- name: Configure supervisor init script
  template: src=supervisord.sh.j2 dest=/etc/init.d/supervisord owner=root group=root mode=0755
  notify:
    - supervisor start
